image: maven:3.5.4-jdk-8
stages:
  - test
  - deploy

lint:
  stage: test
  script:
    - mvn checkstyle:check

deploy:
  only:
    - master
    - develop
  stage: deploy
  script:
    - bash deploy.sh
